import { Flex, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Body from "../src/components/Body";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import Nav from "../src/components/Nav";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Beach Cities General Construction</title>
        <meta
          name="Beach Cities General Construction"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex h="100vh" w="100vw" flexDir="column">
        <Header border="1px solid red" />
        <Nav border="1px solid blue" />
        <Body border="1px solid yellow" />
        <Footer border="1px solid green" />
      </Flex>
    </div>
  );
};

export default Home;
