import { Flex, Box } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Body from "../src/components/Body";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import Nav from "../src/components/Nav";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Beach Cities General Construction</title>
        <meta
          name="Beach Cities General Construction"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon_logo.ico" />
      </Head>
      <Flex flexDir="column">
        <Header />
        <Body />
        <Footer />
      </Flex>
    </Box>
  );
};

export default Home;
